#!/usr/bin/env python3
"""
Add Hindi names (हिंदी नाम) to pfaf_plants_merged.csv
for the Dravya-labs2 Ayurvedic herbal medicine project.
"""

import csv
import os

# Comprehensive mapping: Latin name -> Hindi name (Devanagari)
HINDI_NAMES = {
    # ========== Core Ayurvedic Herbs (from herbs.json) ==========
    "Withania somnifera": "अश्वगंधा",
    "Asparagus racemosus": "शतावरी",
    "Bacopa monnieri": "ब्राह्मी",
    "Phyllanthus emblica": "आंवला",
    "Ocimum tenuiflorum": "तुलसी",
    "Ocimum sanctum": "तुलसी",
    "Curcuma longa": "हल्दी",
    "Tinospora cordifolia": "गिलोय",
    "Azadirachta indica": "नीम",
    "Zingiber officinale": "अदरक",
    "Convolvulus pluricaulis": "शंखपुष्पी",
    "Glycyrrhiza glabra": "मुलेठी",
    "Commiphora mukul": "गुग्गुलु",
    "Terminalia arjuna": "अर्जुन",
    "Acorus calamus": "वच",
    "Boerhavia diffusa": "पुनर्नवा",
    "Picrorhiza kurroa": "कुटकी",
    "Embelia ribes": "विडंग",
    "Eclipta alba": "भृंगराज",
    "Eclipta prostrata": "भृंगराज",
    "Terminalia chebula": "हरीतकी",
    "Terminalia bellirica": "बहेड़ा",
    "Centella asiatica": "गोटू कोला / मण्डूकपर्णी",
    "Commiphora wightii": "गुग्गुलु",
    "Piper nigrum": "काली मिर्च",
    "Piper longum": "पिप्पली",
    "Cinnamomum verum": "दालचीनी",
    "Cinnamomum zeylanicum": "दालचीनी",
    "Cinnamomum tamala": "तेजपत्ता",
    "Elettaria cardamomum": "इलायची",
    "Syzygium aromaticum": "लौंग",
    "Eugenia caryophyllus": "लौंग",
    "Foeniculum vulgare": "सौंफ",
    "Cuminum cyminum": "जीरा",
    "Coriandrum sativum": "धनिया",
    "Trigonella foenum-graecum": "मेथी",
    "Carum carvi": "शाही जीरा",
    "Trachyspermum ammi": "अजवाइन",
    "Crocus sativus": "केसर",
    "Myristica fragrans": "जायफल",
    "Santalum album": "चंदन",
    "Pterocarpus santalinus": "लाल चंदन",
    "Aegle marmelos": "बेल",
    "Saraca asoca": "अशोक",
    "Saraca indica": "अशोक",
    "Moringa oleifera": "सहजन",
    "Andrographis paniculata": "कालमेघ",
    "Rauvolfia serpentina": "सर्पगंधा",
    "Coleus forskohlii": "पाषाणभेद",
    "Plectranthus barbatus": "पत्थरचट्टा",
    "Catharanthus roseus": "सदाबहार",
    "Mucuna pruriens": "कौंच बीज",
    "Cannabis sativa": "भांग",
    "Lawsonia inermis": "मेहंदी",
    "Aloe vera": "घृतकुमारी / एलोवेरा",
    "Aloe barbadensis": "घृतकुमारी / एलोवेरा",
    "Nardostachys jatamansi": "जटामांसी",
    "Vetiveria zizanioides": "खस",
    "Chrysopogon zizanioides": "खस",
    "Berberis aristata": "दारूहल्दी",
    "Swertia chirayita": "चिरायता",
    "Aconitum heterophyllum": "अतीस",
    "Aconitum ferox": "वत्सनाभ",

    # ========== Common Indian Vegetables & Fruits ==========
    "Solanum melongena": "बैंगन",
    "Solanum tuberosum": "आलू",
    "Solanum lycopersicum": "टमाटर",
    "Capsicum annuum": "शिमला मिर्च",
    "Capsicum frutescens": "लाल मिर्च",
    "Allium cepa": "प्याज",
    "Allium sativum": "लहसुन",
    "Allium tuberosum": "चाइनीज़ चाइव्स",
    "Allium fistulosum": "हरा प्याज",
    "Mangifera indica": "आम",
    "Carica papaya": "पपीता",
    "Punica granatum": "अनार",
    "Musa paradisiaca": "केला",
    "Musa acuminata": "केला",
    "Cocos nucifera": "नारियल",
    "Tamarindus indica": "इमली",
    "Citrus limon": "नींबू",
    "Citrus sinensis": "संतरा",
    "Citrus aurantium": "खट्टा संतरा",
    "Citrus medica": "नींबू / बिजौरा",
    "Citrus reticulata": "सन्तरा / कीनू",
    "Psidium guajava": "अमरूद",
    "Phoenix dactylifera": "खजूर",
    "Vitis vinifera": "अंगूर",
    "Artocarpus heterophyllus": "कटहल",
    "Annona squamosa": "शरीफा / सीताफल",
    "Litchi chinensis": "लीची",
    "Ziziphus jujuba": "बेर",
    "Ziziphus mauritiana": "बेर",
    "Syzygium cumini": "जामुन",
    "Syzygium jambos": "गुलाब जामुन",
    "Ananas comosus": "अनानास",
    "Artocarpus altilis": "ब्रेडफ्रूट",
    "Cucumis sativus": "खीरा",
    "Cucumis melo": "खरबूजा",
    "Citrullus lanatus": "तरबूज़",
    "Lagenaria siceraria": "लौकी",
    "Momordica charantia": "करेला",
    "Momordica dioica": "ककोड़ा",
    "Luffa cylindrica": "तोरई",
    "Luffa acutangula": "तोरई",
    "Trichosanthes cucumerina": "परवल",
    "Trichosanthes dioica": "परवल",
    "Benincasa hispida": "पेठा",
    "Coccinia grandis": "कुंदरू",
    "Spinacia oleracea": "पालक",
    "Amaranthus viridis": "चौलाई",
    "Amaranthus cruentus": "चौलाई",
    "Amaranthus tricolor": "चौलाई",
    "Raphanus sativus": "मूली",
    "Daucus carota": "गाजर",
    "Beta vulgaris": "चुकंदर",
    "Brassica oleracea": "पत्तागोभी",
    "Brassica rapa": "शलगम",
    "Brassica juncea": "सरसों",
    "Brassica nigra": "राई",
    "Abelmoschus esculentus": "भिंडी",
    "Ipomoea batatas": "शकरकंद",
    "Colocasia esculenta": "अरबी",
    "Dioscorea alata": "रतालू",

    # ========== Pulses & Grains ==========
    "Lens culinaris": "मसूर दाल",
    "Cicer arietinum": "चना",
    "Vigna radiata": "मूंग दाल",
    "Vigna mungo": "उड़द दाल",
    "Vigna unguiculata": "लोबिया",
    "Cajanus cajan": "अरहर / तुअर दाल",
    "Phaseolus vulgaris": "राजमा",
    "Phaseolus lunatus": "सेम",
    "Arachis hypogaea": "मूंगफली",
    "Glycine max": "सोयाबीन",
    "Pisum sativum": "मटर",
    "Oryza sativa": "चावल",
    "Triticum aestivum": "गेहूं",
    "Hordeum vulgare": "जौ",
    "Zea mays": "मक्का",
    "Sorghum bicolor": "ज्वार",
    "Pennisetum glaucum": "बाजरा",
    "Eleusine coracana": "रागी / मंडुआ",
    "Sesamum indicum": "तिल",
    "Linum usitatissimum": "अलसी",
    "Saccharum officinarum": "गन्ना",
    "Gossypium herbaceum": "कपास",
    "Gossypium arboreum": "कपास",

    # ========== Medicinal & Aromatic Plants ==========
    "Rosa damascena": "गुलाब",
    "Rosa centifolia": "गुलाब",
    "Rosa indica": "देसी गुलाब",
    "Jasminum officinale": "चमेली",
    "Jasminum sambac": "मोगरा",
    "Jasminum grandiflorum": "चमेली",
    "Hibiscus rosa-sinensis": "गुड़हल",
    "Hibiscus sabdariffa": "गुड़हल / रोसेला",
    "Nyctanthes arbor-tristis": "हरसिंगार",
    "Ocimum basilicum": "बनतुलसी",
    "Ocimum gratissimum": "राम तुलसी",
    "Mentha piperita": "पुदीना",
    "Mentha spicata": "पुदीना",
    "Mentha arvensis": "पुदीना",
    "Cymbopogon citratus": "लेमनग्रास",
    "Cymbopogon flexuosus": "लेमनग्रास",
    "Cymbopogon martinii": "पामारोसा",
    "Origanum vulgare": "अजवायन की पत्ती",
    "Thymus vulgaris": "अजवायन के फूल",
    "Rosmarinus officinalis": "रोज़मेरी",
    "Salvia officinalis": "सेज",
    "Calendula officinalis": "गेंदा",
    "Tagetes erecta": "गेंदा",
    "Chrysanthemum indicum": "गुलदाउदी",
    "Ricinus communis": "अरंडी",
    "Plantago ovata": "इसबगोल",
    "Plantago major": "इसबगोल",
    "Cassia fistula": "अमलतास",
    "Cassia angustifolia": "सनाय / सेना",
    "Senna alexandrina": "सनाय / सेना",
    "Butea monosperma": "पलाश",
    "Dalbergia sissoo": "शीशम",
    "Bauhinia variegata": "कचनार",
    "Bauhinia purpurea": "कचनार",
    "Sapindus mukorossi": "रीठा",
    "Sapindus trifoliatus": "रीठा",
    "Acacia nilotica": "बबूल",
    "Acacia catechu": "खैर",
    "Acacia arabica": "बबूल",
    "Acacia farnesiana": "विलायती बबूल",
    "Shorea robusta": "साल",
    "Tectona grandis": "सागौन",
    "Bambusa bambos": "बांस",
    "Bambusa vulgaris": "बांस",
    "Dendrocalamus strictus": "बांस",
    "Ficus religiosa": "पीपल",
    "Ficus benghalensis": "बरगद",
    "Ficus carica": "अंजीर",
    "Ficus racemosa": "गूलर",
    "Ficus glomerata": "गूलर",
    "Melia azedarach": "बकायन",
    "Cedrus deodara": "देवदार",
    "Pinus roxburghii": "चीड़",
    "Emblica officinalis": "आंवला",
    "Semicarpus anacardium": "भिलावा",
    "Strychnos nux-vomica": "कुचला",
    "Abrus precatorius": "गुंजा / रत्ती",
    "Achyranthes aspera": "अपामार्ग / चिरचिटा",
    "Adhatoda vasica": "अड़ूसा / वासा",
    "Justicia adhatoda": "अड़ूसा / वासा",
    "Withania coagulans": "पनीर डोडी",
    "Tribulus terrestris": "गोखरू",
    "Asparagus adscendens": "सफेद मूसली",
    "Chlorophytum borivilianum": "सफेद मूसली",
    "Curculigo orchioides": "काली मूसली",
    "Pueraria tuberosa": "विदारीकंद",
    "Sida cordifolia": "बला",
    "Cyperus rotundus": "नागरमोथा / मुस्तक",
    "Alpinia galanga": "कुलंजन",
    "Curcuma aromatica": "जंगली हल्दी",
    "Curcuma zedoaria": "कचूर",
    "Curcuma amada": "आम हल्दी",
    "Inula racemosa": "पुष्करमूल",
    "Pongamia pinnata": "करंज",
    "Madhuca longifolia": "महुआ",
    "Symplocos racemosa": "लोध्र",
    "Mesua ferrea": "नागकेसर",
    "Calotropis gigantea": "आक / मदार",
    "Calotropis procera": "आक / मदार",
    "Datura stramonium": "धतूरा",
    "Datura metel": "धतूरा",
    "Nerium oleander": "कनेर",
    "Plumeria rubra": "चंपा",
    "Michelia champaca": "चम्पा",
    "Nelumbo nucifera": "कमल",
    "Nymphaea stellata": "नीलकमल",
    "Cissus quadrangularis": "हड़जोड़",
    "Euphorbia hirta": "दूधी",
    "Emblica ribes": "विडंग",
    "Ferula assa-foetida": "हींग",
    "Ferula foetida": "हींग",
    "Phyllanthus niruri": "भूमि आंवला",
    "Tinospora sinensis": "गिलोय",
    "Gymnema sylvestre": "गुड़मार",
    "Ocimum canum": "तुलसी",
    "Hemidesmus indicus": "अनंतमूल",
    "Celastrus paniculatus": "ज्योतिष्मती",
    "Operculina turpethum": "त्रिवृत / निसोथ",
    "Barleria prionitis": "सहचर / वज्रदंती",
    "Clerodendrum serratum": "भारंगी",
    "Smilax china": "चोबचीनी",
    "Cissampelos pareira": "पाठा",
    "Gentiana kurroo": "कुटकी",
    "Valeriana jatamansi": "तगर",
    "Valeriana officinalis": "तगर",
    "Rubia cordifolia": "मजीठ",
    "Fumaria indica": "पित्तपापड़ा",
    "Fumaria officinalis": "पित्तपापड़ा",
    "Solanum nigrum": "मकोय",
    "Solanum xanthocarpum": "कंटकारी",
    "Solanum virginianum": "कंटकारी",
    "Desmodium gangeticum": "शालपर्णी",
    "Uraria picta": "पृश्निपर्णी",
    "Premna integrifolia": "अग्निमंथ",
    "Oroxylum indicum": "श्योनाक",
    "Gmelina arborea": "गंभारी",
    "Stereospermum chelonoides": "पाटला",
    "Clerodendrum phlomidis": "अग्निमंथ",
    "Shorea talura": "साल",
    "Cedrus libani": "देवदार",

    # ========== Trees & Common Plants ==========
    "Prosopis cineraria": "खेजड़ी",
    "Azadirachta indica": "नीम",
    "Eucalyptus globulus": "नीलगिरी",
    "Wrightia tinctoria": "इंद्रजव / कुटज",
    "Holarrhena pubescens": "कुटज",
    "Holarrhena antidysenterica": "कुटज",
    "Taxus baccata": "थुनेर",
    "Adansonia digitata": "गोरख इमली",
    "Bombax ceiba": "सेमल",
    "Ceiba pentandra": "सेमल",

    # ========== More Spices & Condiments ==========
    "Curcuma caesia": "काली हल्दी",
    "Piper retrofractum": "पिप्पली",
    "Piper betle": "पान",
    "Piper cubeba": "कबाबचीनी",
    "Syzygium aromaticum": "लौंग",
    "Cinnamomum cassia": "दालचीनी",
    "Cinnamomum camphora": "कपूर",
    "Illicium verum": "चक्र फूल / स्टार ऐनिस",
    "Nigella sativa": "कलौंजी",
    "Sesamum indicum": "तिल",
    "Papaver somniferum": "अफीम / पोस्त",
    "Tamarindus indica": "इमली",
    "Garcinia indica": "कोकम",
    "Cocos nucifera": "नारियल",
    "Curcuma angustifolia": "तिखुर",
}

def main():
    input_file = os.path.join(os.path.dirname(__file__), "pfaf_plants_merged.csv")
    output_file = os.path.join(os.path.dirname(__file__), "pfaf_plants_hindi.csv")

    rows_with_hindi = 0
    total_rows = 0

    with open(input_file, "r", encoding="utf-8") as fin:
        reader = csv.DictReader(fin)
        fieldnames = reader.fieldnames + ["hindi_name"]

        with open(output_file, "w", encoding="utf-8", newline="") as fout:
            writer = csv.DictWriter(fout, fieldnames=fieldnames)
            writer.writeheader()

            for row in reader:
                total_rows += 1
                latin_name = row.get("latin_name_search", "").strip()

                # Try exact match first
                hindi = HINDI_NAMES.get(latin_name, "")

                # If no exact match, try genus-level match for some well-known genera
                if not hindi:
                    genus = latin_name.split()[0] if latin_name else ""
                    genus_map = {
                        "Curcuma": "हल्दी वर्ग",
                        "Ocimum": "तुलसी वर्ग",
                        "Cinnamomum": "दालचीनी वर्ग",
                        "Piper": "मिर्च/पीपल वर्ग",
                        "Terminalia": "हरड़ वर्ग",
                        "Ficus": "वट वर्ग",
                        "Berberis": "दारूहल्दी वर्ग",
                    }
                    hindi = genus_map.get(genus, "")

                row["hindi_name"] = hindi
                if hindi:
                    rows_with_hindi += 1
                writer.writerow(row)

    print(f"✅ Done! Output saved to: {output_file}")
    print(f"   Total rows: {total_rows}")
    print(f"   Rows with Hindi names: {rows_with_hindi}")
    print(f"   Coverage: {rows_with_hindi/total_rows*100:.1f}%")

if __name__ == "__main__":
    main()
